# patients_xlsx = "https://drive.google.com/uc?export=download&id=1ElxGwoKobfUkBaryPu1o5bnkWx2iUdHc"
# inspections_xlsx = "https://drive.google.com/uc?export=download&id=1dhjaRyKGFai_rOHjmdjrQq2rtpG5UKq8"
patients_and_inspections_xlsx = "https://drive.google.com/uc?export=download&id=1nYmo2Wz84yvA99g1QjlwsjA_b6keAodN"
contacts1_xlsx = "https://drive.google.com/uc?export=download&id=12iu150zglIHTS0CpRcY3GUG6whUH5N69"
contacts2_xlsx = "https://drive.google.com/uc?export=download&id=1JW9yE7yA_hx1ZVFNlgUJX774EWVZ9IQz"
news_url = "http://www.pref.osaka.lg.jp/hodo/index.php?HST_BUCODE=6000&SEARCH_NUM=50&site=fumin&start=1"
